export const GET_PRODUCTS_LOAD= "GET_PRODUCTS_LOAD";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";


export const TOGGLE_TRUE = "TOGGLE_TRUE";
export const TOGGLE_FALSE = "TOGGLE_FALSE";